export const MENU_CATEGORIES = [
  {
    name: '전체 메뉴',
    image: '/images/menu-categories/all.png',
    category: 'all',
  },
  {
    name: '세트 메뉴',
    image: '/images/menu-categories/set.png',
    category: 'set',
  },
  {
    name: '함박 메뉴',
    image: '/images/menu-categories/hambak.png',
    category: 'hambak',
  },
  {
    name: '스페셜 메뉴',
    image: '/images/menu-categories/special.png',
    category: 'special',
  },
  {
    name: '사이드 메뉴',
    image: '/images/menu-categories/side.png',
    category: 'side',
  },
  {
    name: '음료 / 주류',
    image: '/images/menu-categories/drink.png',
    category: 'drink',
  },
];

export const MENU_ITEMS = [
  {
    id: 1,
    name: '고동함박',
    description: '울 할머니 오리지널 레시피^^ 새콤달콤 함박스떼끼 소스',
    price: 10900,
    image: '/images/menu/01.png',
    category: 'hambak',
  },
  {
    id: 2,
    name: '깔매함박',
    description: '깔끔, 매콤하게 중독성 강한 옛날 떡볶이 소스 위에 치즈 폭탄!',
    price: 11900,
    image: '/images/menu/02.png',
    category: 'hambak',
  },
  {
    id: 3,
    name: '로제함박',
    description: '부드러운 리얼 로제크림소스',
    price: 13500,
    image: '/images/menu/03.png',
    category: 'hambak',
  },
  {
    id: 4,
    name: '월클함박',
    description: '월클소스와 신선한 샐러드와의 조합',
    price: 13900,
    image: '/images/menu/04.png',
    category: 'hambak',
  },
  {
    id: 5,
    name: '고순까스',
    description: '겉은 바삭! 속은 육즙 가득 극각의 겉.바.속.촉',
    price: 13900,
    image: '/images/menu/05.png',
    category: 'hambak',
  },
  {
    id: 6,
    name: '혜자버거',
    description: '울엄마 혜자씨의 NO.1 수제버거',
    price: 11500,
    image: '/images/menu/06.png',
    category: 'hambak',
  },
  {
    id: 7,
    name: '토마토 파스타',
    description: '멋쟁이 토마토 소개로 만난 함박과 파스타',
    price: 12500,
    image: '/images/menu/07.png',
    category: 'special',
  },
  {
    id: 8,
    name: '문래 돈까스',
    description: '두툼한 국내산 100% 촉촉 고소한 수제 돈까스',
    price: 11900,
    image: '/images/menu/08.png',
    category: 'special',
  },
  {
    id: 9,
    name: '쫄면',
    description: '새콤, 달콤, 매콤 매점 쫄면',
    price: 5500,
    image: '/images/menu/09.png',
    category: 'side',
  },
  {
    id: 10,
    name: '샐러드',
    description: '야채는 신선이지!',
    price: 6500,
    image: '/images/menu/10.png',
    category: 'side',
  },
  {
    id: 11,
    name: '순대튀김',
    description: '안녕~ 찰 순대라고해',
    price: 5900,
    image: '/images/menu/11.png',
    category: 'side',
  },
  {
    id: 12,
    name: '새우튀김',
    description: '별이 여섯개! 왕새우',
    price: 6900,
    image: '/images/menu/12.png',
    category: 'side',
  },
  {
    id: 13,
    name: '치즈 포테이토',
    description: '오리지널 감자튀김',
    price: 7900,
    image: '/images/menu/13.png',
    category: 'side',
  },
  {
    id: 14,
    name: '날아라 봉봉',
    description: '크리스피 치킨봉',
    price: 8900,
    image: '/images/menu/14.png',
    category: 'side',
  },
  {
    id: 15,
    name: '고동 세트',
    description: '고동함박 + 미니 쫄면 + 음료',
    price: 16900,
    image: '/images/menu/15.png',
    category: 'set',
  },
  {
    id: 16,
    name: '깔매 세트',
    description: '깔매함박 + 반순대 + 음료',
    price: 15900,
    image: '/images/menu/16.png',
    category: 'set',
  },
  {
    id: 17,
    name: '고순 세트',
    description: '고순까스 + 미니 쫄면 + 음료',
    price: 18900,
    image: '/images/menu/17.png',
    category: 'set',
  },
  {
    id: 18,
    name: '혜자 세트',
    description: '혜자 버거 + 날아라 봉봉 + 음료',
    price: 16900,
    image: '/images/menu/18.png',
    category: 'set',
  },
];
